# Generated by Django 4.0.2 on 2022-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('source', models.CharField(choices=[('gu', 'Guardian UK'), ('hn', 'Historical News'), ('go', 'Google')], default='gu', max_length=2)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
